# .air.toml
root = "."
tmp_dir = "tmp"

[build]
# 只需要写构建命令，air 会自动执行
cmd = "go build -o ./tmp/main ."
# 编译出的二进制文件位置
bin = "./tmp/main"
# 监听的文件扩展名
include_ext = ["go", "tpl", "tmpl", "html", "yaml"]
# 忽略的目录
exclude_dir = ["assets", "tmp", "vendor", "logs"]
# 忽略的文件
exclude_file = []
# 发生构建错误时是否延迟
delay = 1000 # ms
# 停止旧进程时发送的信号
stop_on_error = true
log = "air_errors.log"

[log]
time = true

[misc]
clean_on_exit = true